{
  "comments": [
    {
      "key": {
        "uuid": "9ab8dda7_281d1510",
        "filename": "functest/utils/openstack_utils.py",
        "patchSetId": 5
      },
      "lineNbr": 155,
      "author": {
        "id": 2175
      },
      "writtenOn": "2017-03-21T07:58:16Z",
      "side": 1,
      "message": "Should https_insecure be set as true in rally conf if no cacert available?",
      "revId": "4a989722feca53e1baa6f64985841bd6a244d627",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9ab8dda7_0895b13f",
        "filename": "functest/utils/openstack_utils.py",
        "patchSetId": 5
      },
      "lineNbr": 155,
      "author": {
        "id": 5959
      },
      "writtenOn": "2017-03-21T08:24:57Z",
      "side": 1,
      "message": "Do you mean the case:\nthe OS_CACERT is set while the referred cacert file does not exist?\n\nI tested the case that OS_CACERT is set and the corresponding cacert file exists and the current code is working.",
      "parentUuid": "9ab8dda7_281d1510",
      "revId": "4a989722feca53e1baa6f64985841bd6a244d627",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9ab8dda7_9304727f",
        "filename": "functest/utils/openstack_utils.py",
        "patchSetId": 5
      },
      "lineNbr": 155,
      "author": {
        "id": 2175
      },
      "writtenOn": "2017-03-21T12:23:13Z",
      "side": 1,
      "message": "I mean the case when https is enabled but there\u0027s no cacert file. I.e. when one have to use \u0027--insecure\u0027 option in openstack cli commands.",
      "parentUuid": "9ab8dda7_0895b13f",
      "revId": "4a989722feca53e1baa6f64985841bd6a244d627",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}