{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_df507760",
        "filename": "testcases/Controllers/ONOS/Teston/onosfunctest.py",
        "patchSetId": 2
      },
      "lineNbr": 269,
      "author": {
        "id": 459
      },
      "writtenOn": "2016-09-12T09:47:55Z",
      "side": 1,
      "message": "@Meimei: you said: we need a check of return value in main, otherwise the return fail doesn\u0027t work. It is that still to be implemented here?",
      "revId": "64d20d06573ca64c67e794980dc76f66ffbe9c6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}