{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_669305fb",
        "filename": "testcases/OpenStack/vPing/vping.py",
        "patchSetId": 1
      },
      "lineNbr": 53,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-08-23T06:44:13Z",
      "side": 1,
      "message": "I would have preferred not exiting on errors in util.create_image. you could check here image_id and exit if necessary.",
      "revId": "73053cd38fed875e3e5d64cabfb7fbfeb2839a80",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_a65efd43",
        "filename": "testcases/OpenStack/vPing/vping.py",
        "patchSetId": 1
      },
      "lineNbr": 53,
      "author": {
        "id": 2651
      },
      "writtenOn": "2016-08-23T07:00:49Z",
      "side": 1,
      "message": "Sorry, I don\u0027t get your point clearly. if not exiting on errors, the following work will failed, there\u0027s no point in proceeding if image is not exist and create failed.",
      "parentUuid": "1a76adc5_669305fb",
      "revId": "73053cd38fed875e3e5d64cabfb7fbfeb2839a80",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}