{
  "comments": [
    {
      "key": {
        "uuid": "5ac10518_2d88cde6",
        "filename": "utils/config_functest.py",
        "patchSetId": 8
      },
      "lineNbr": 12,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-10-26T08:45:33Z",
      "side": 1,
      "message": "I think it could raise exceptions.\nYou could move it to __init__() + catch exception.",
      "revId": "73c9746fe56aca6d721212d9fbf1448a4334739a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5ac10518_ad735d14",
        "filename": "utils/config_functest.py",
        "patchSetId": 8
      },
      "lineNbr": 461,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-10-26T08:45:33Z",
      "side": 1,
      "message": "functest_yaml could be checked.",
      "range": {
        "startLine": 461,
        "startChar": 25,
        "endLine": 461,
        "endChar": 26
      },
      "revId": "73c9746fe56aca6d721212d9fbf1448a4334739a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}