{
  "comments": [
    {
      "key": {
        "uuid": "dabed58f_689556e3",
        "filename": "functest/ci/prepare_env.py",
        "patchSetId": 4
      },
      "lineNbr": 228,
      "author": {
        "id": 2651
      },
      "writtenOn": "2017-02-16T10:18:42Z",
      "side": 1,
      "message": "if cmd execute fail will raise exception everywhere, how about raise exception in execute_command?",
      "revId": "da6bcabf8c84f1891e39bf78b135c90e1f219136",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dabed58f_684a3685",
        "filename": "functest/ci/prepare_env.py",
        "patchSetId": 4
      },
      "lineNbr": 228,
      "author": {
        "id": 5959
      },
      "writtenOn": "2017-02-16T10:45:43Z",
      "side": 1,
      "message": "I was thinking in the same way earlier. However, I changed my mind.The execute_command is called by many modules. If it is changed, it\u0027s likely to induce regression while we are in a release phase that cannot afford the risk.\n\nAlso, there are some cases though the command fails but the process should continue. e.g.\nrally deployment destroy opnfv-rally, it fails if the opnfv-rally does not exist. We can check the existence of it first and only delete when it exists. We can also delete it if it exists and ignore the error if it does not exist(current way). If raise exception, the execution will be stopped.",
      "parentUuid": "dabed58f_689556e3",
      "revId": "da6bcabf8c84f1891e39bf78b135c90e1f219136",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}